name: api_course
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3+1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  lint: ^1.8.2

flutter:
  uses-material-design: true
